### ISSUE TITLE
includeIndices causes memory leak when adding many times

### ISSUE THREAD

**Issue by astanway** [mikera/vectorz#81]
I've got a very large matrix where I need to add a vector to a column, perform an operation, and then subtract the original vector (leaving me with what should be the original matrix).

However, I'm experiencing a memory leak because of (I believe) the `includeIndices` functions, which seem to be really eating up space every time I add and subtract.

Here's my code: 

```
        // oldMatrix is a SparseRowMatrix made of SparseIndexedVectors
        SparseColumnMatrix proximities = oldMatrix.toSparseColumnMatrix();
        for (int index = 0; index < matrixSize; index++) {
            matrix.getColumnView(index).add(vector);

            // do other things

            matrix.getColumnView(index).sub(vector);
        }
```

Any ideas on this behavior from `includeIndices`?

**Comment by mikera** [comment]
What is the type of the matrix?

I assume it is some composition of SparseIndexedVectors, in which case currently we don't auto-compact the indexes when elements are set back to zero, which would cause memory usage to expand if you do this frequently on large matrices. This would be possible, but it would hurt performance in other areas because re-compacting is quite expensive.

Good workarounds might be to either:

a) use `replaceColumn` to replace the column in place, then set the column back to the original column after your inner operations
b) Write code to re-compact the columns by reconstructing the whole sparse matrix after use (sort of like a Garbage Collect for sparse matrices....)

**Comment by astanway** [comment]
Yep, it's a composition of SparseIndexedVectors. I switched to replacing columns and it did seem to fix the leak - thank you!

As an aside - why is it necessary to use SparseIndexedVectors within a SparseColumnMatrix/SparseRowMatrix? (I'm doing it as per http://stackoverflow.com/questions/20767397/efficient-modification-of-the-rows-of-a-sparse-matrix-in-java). It seems like the sparse matrices should already be optimized for getRow() and getColumn() without using the SparseIndexedVectors, right?

**Comment by mikera** [comment]
SparseRowMatrix and SparseColumnMatrix use SparseIndexedVectors for the rows / columns respectively as an implementation detail.


You can use any other vector types for rows / columns if you like.

**Comment by mikera** [comment]
Closing this as I think you have a good solution.
