### ISSUE TITLE
Slow SparseColumnMatrix innerProduct

### ISSUE THREAD

**Issue by malloc82** [mikera/vectorz#84]
SparseColumnMatrix's innerProduct function is extremely slow with the current implementation. I was using it on a 40000x41262 SparseColumnMatrix, it took almost 6 min (531215.413798 msecs). The following clojure implementation is able to produce the same output around 1 second on the same machine. 

```clojure
(defn innerProduct
  [^SparseColumnMatrix A ^Vector x]
  (let [_M ^SparseColumnMatrix (m/clone A)
        b  ^Vector  (Vector/createLength (m/row-count _M))
        N  ^Integer (int (m/column-count _M))]
    (dotimes [c N]
      (let [col (.getColumn _M c)]
        (.multiply col (.get x c))
        (.add b col)))
    b))
```
I think the addMultipleToArray method is not very memory efficient.

**Comment by malloc82** [comment]
Oops, should probably use exactClone method. It seems if I just call clone from core.matrix, it sometimes will return a regular matrix instead, but for large sparse matrix it still returns a sparse one.
```clojure
(defn innerProduct
  [^SparseColumnMatrix A ^Vector x]
  (let [_M ^SparseColumnMatrix (.exactClone A)
        b  ^Vector  (Vector/createLength (m/row-count _M))
        N  ^Integer (int (m/column-count _M))]
    (dotimes [c N]
      (let [col (.getColumn _M c)]
        (.multiply col (.get x c))
        (.add b col)))
    b))
```
Timing wise, there is no difference for the 40000x41262 test case, it's under 1 second.

**Comment by mikera** [comment]
Thanks for the report. In general, you have to use some care when selecting specialised matrix types - some are optimised for specific operations at the expense of others.

The idea in general is that SparseRowMatrix is better for the first argument of inner products, and SparseColumnMatrix is better as the second arguments (this is because the memory layout is better suited for calculations that way around)

I'll take a look at this specific issue however, 6 mins is way too slow....

**Comment by mikera** [comment]
Can you post an example of the code that is really slow?

**Comment by mikera** [comment]
Ah don't worry I found the problem. The problem was AMatrix.transform(Vector) had not been overridden for SparseColumnMatrix

Will be fixed in next release

**Comment by malloc82** [comment]
Awesome, thanks!
